name: Test Linux ARM64 on GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  run-arm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Run ARM64 Docker Container
        run: |
          docker run --rm --platform linux/arm64 alpine:latest uname -m
